---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
    # 1st: check syntax
    - ansible-playbook -i tests/inv.ini tests/test_travis.yml --syntax-check

    # 2nd:  Make sure we run the entire playbook
    - ansible-playbook -i tests/inv.ini tests/test_travis.yml --sudo

    # 3rd:  Make sure our playbook is idempotent 
    - >
      ansible-playbook -i tests/inv.ini tests/test_travis.yml --sudo
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

    # 4th:  Application test
    # Nothing for this role 

